import { test, expect } from '@playwright/test'
const routes = ['/', '/tentang-kami', '/layanan', '/layanan/konstruksi-gedung', '/layanan/renovasi-interior', '/layanan/perencanaan', '/layanan/infrastruktur', '/galeri', '/proyek/gedung-perkantoran', '/proyek/hunian-tropis', '/proyek/ruang-kolaborasi', '/proyek/pengembangan-kawasan', '/proyek/pusat-usaha', '/proyek/studio-kreatif', '/artikel', '/artikel/merencanakan-anggaran', '/artikel/renovasi-ruang-kerja', '/artikel/koordinasi-proyek', '/kontak', '/faq', '/kebijakan-privasi']
test('halaman perusahaan, metadata, dan tata letak', async ({ page }) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  page.on('console', m => { if (/hydration/i.test(m.text())) errors.push(m.text()) })
  const titles = new Set()
  for (const route of routes) {
    const response = await page.goto(route)
    expect(response?.status(), route).toBe(200)
    await expect(page.locator('html')).toHaveAttribute('lang', 'id')
    await expect(page.locator('h1')).toHaveCount(1)
    await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', /.+/)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), route).toBe(true)
    expect(await page.locator('main').innerText()).not.toMatch(/Muhamad Fajar|Full Stack Developer/)
    titles.add(await page.title())
  }
  expect(titles.size).toBe(routes.length)
  expect(errors).toEqual([])
})
test('filter galeri dan detail proyek', async ({ page }) => {
  await page.goto('/galeri')
  await page.getByRole('button', { name: 'Renovasi', exact: true }).click()
  await expect(page.locator('.content-card')).toHaveCount(2)
  await page.locator('.content-card').first().click()
  await expect(page).toHaveURL(/\/proyek\//)
  await expect(page.locator('.prose-content')).toContainText('studi ilustratif')
})
test('pencarian artikel, hasil kosong, dan reset', async ({ page }) => {
  await page.goto('/artikel')
  await page.getByRole('textbox', { name: 'Cari artikel' }).fill('anggaran')
  await expect(page.locator('.content-card')).toHaveCount(1)
  await page.getByRole('textbox', { name: 'Cari artikel' }).fill('tidak-ada-artikel-ini')
  await expect(page.getByText('Artikel belum ditemukan.')).toBeVisible()
  await page.getByRole('button', { name: 'Reset Pencarian' }).click()
  await expect(page.locator('.content-card')).toHaveCount(3)
  await page.locator('.content-card').first().click()
  await expect(page.locator('.prose-content h2').first()).toBeVisible()
})
test('formulir kontak empat kolom tervalidasi dan menyiapkan email', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/kontak')
  await expect(page.locator('.contact-form input')).toHaveCount(3)
  await expect(page.locator('.contact-form textarea')).toHaveCount(1)
  await page.getByRole('button', { name: 'Siapkan Pesan', exact: true }).click()
  await expect(page.getByText('Masukkan nama minimal 2 karakter.')).toBeVisible()
  await expect(page.getByText('Masukkan nomor telepon yang valid (8–15 digit).')).toBeVisible()
  await page.getByRole('textbox', { name: 'Nama lengkap' }).fill('Budi Santoso')
  await page.getByRole('textbox', { name: 'Nomor telepon' }).fill('081234567890')
  await page.getByRole('textbox', { name: 'Alamat email' }).fill('budi@example.com')
  await page.getByRole('textbox', { name: 'Pesan', exact: false }).fill('Saya ingin berkonsultasi tentang pembangunan rumah di Sukabumi.')
  await page.getByRole('button', { name: 'Siapkan Pesan', exact: true }).click()
  await expect(page.getByText('Pesan siap diteruskan.')).toBeVisible()
  const email = await page.getByRole('link', { name: 'Buka Aplikasi Email' }).getAttribute('href')
  expect(email).toContain('mailto:halo@alphatunasmandiri.example')
  expect(decodeURIComponent(email!)).toContain('081234567890')
  await page.getByRole('button', { name: 'Salin Pesan', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Pesan berhasil disalin.')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('Budi Santoso')
  await page.getByRole('textbox', { name: 'Nama lengkap' }).fill('Budi Baru')
  await expect(page.locator('.summary-panel')).not.toBeVisible()
})
test('WhatsApp dua admin, penutupan, dan peta Sukabumi', async ({ page, context }, testInfo) => {
  test.setTimeout(60000)
  await context.route('https://wa.me/**', route => route.fulfill({ status: 200, contentType: 'text/html', body: '<title>WhatsApp test</title>' }))
  await page.goto('/kontak')
  const trigger = page.getByRole('button', { name: 'Hubungi melalui WhatsApp', exact: true })
  await expect(trigger).toBeVisible()
  await trigger.click()
  await expect(page.locator('.whatsapp-panel')).toBeVisible()
  await expect(page.locator('.whatsapp-admin')).toHaveCount(2)
  const bounds = await page.locator('.whatsapp-panel').boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.keyboard.press('Escape')
  await expect(page.locator('.whatsapp-panel')).not.toBeVisible()
  await expect(trigger).toBeFocused()
  for (const [name, number] of [['Admin 1', '6281200000001'], ['Admin 2', '6281200000002']]) {
    await trigger.click()
    const link = page.getByRole('link', { name: 'Hubungi ' + name + ' melalui WhatsApp (tab baru)' })
    await expect(link).toHaveAttribute('href', new RegExp('https://wa.me/' + number))
    const popupPromise = context.waitForEvent('page')
    await link.click()
    const popup = await popupPromise
    await expect(popup).toHaveURL(new RegExp('https://wa.me/' + number))
    await popup.close()
    await expect(page.locator('.whatsapp-panel')).not.toBeVisible()
  }
  const map = page.getByTitle('Peta lokasi kantor dummy di Sukabumi')
  await map.scrollIntoViewIfNeeded()
  await expect(map).toHaveAttribute('src', /google.com\/maps\?q=-6.9210%2C106.9270/)
  await expect(page.getByRole('link', { name: 'Petunjuk Arah' })).toHaveAttribute('href', /destination=-6.9210%2C106.9270/)
  await expect(page.frameLocator('iframe.office-map').locator('body')).toBeVisible({ timeout: 20000 })
  await page.evaluate(() => {
    (document.activeElement as HTMLElement)?.blur()
    window.scrollTo({ top: 0, behavior: 'instant' })
  })
  await page.screenshot({ path: 'artifacts/kontak-' + testInfo.project.name + '.png', fullPage: true })
  await trigger.click()
  await page.screenshot({ path: 'artifacts/whatsapp-' + testInfo.project.name + '.png' })
  await page.keyboard.press('Escape')
  await page.goto('/')
  await expect(page.locator('.whatsapp-float')).toHaveCount(0)
  await expect(page.locator('.achievement-section')).toHaveCount(0)
})
test('navigasi seluler, FAQ, dan gerak minimum', async ({ page, isMobile }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  expect(await page.locator('.hero-content').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  if (isMobile) {
    await page.getByRole('button', { name: 'Buka menu' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await page.getByRole('button', { name: 'Buka menu' }).click()
    await page.getByRole('dialog').getByRole('link', { name: 'Tentang Kami', exact: true }).click()
    await expect(page).toHaveURL(/tentang-kami$/)
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  await page.goto('/faq')
  await page.getByRole('button', { name: 'Apa saja layanan yang tersedia?' }).click()
  await expect(page.getByText(/Kami menyiapkan solusi konstruksi gedung/)).toBeVisible()
})
test('tangkapan tampilan dan aset hero', async ({ page }, testInfo) => {
  test.setTimeout(60000)
  await page.goto('/')
  await expect(page.locator('.hero-photo img')).toBeVisible()
  await expect.poll(() => page.locator('.hero-photo img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0), { timeout: 30000 }).toBe(true)
  for (const image of await page.locator('main img').all()) {
    await image.scrollIntoViewIfNeeded()
    await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0), { timeout: 15000 }).toBe(true)
  }
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: 'artifacts/beranda-' + testInfo.project.name + '.png', fullPage: true })
})
