<script setup lang="ts">
const { data: company } = await useCompany()
const { data: services } = await useAsyncData('home-services', () => queryCollection('layanan').order('order', 'ASC').all())
const { data: projects } = await useAsyncData('home-projects', () => queryCollection('proyek').order('order', 'ASC').limit(3).all())
const { data: articles } = await useAsyncData('home-articles', () => queryCollection('artikel').order('date', 'DESC').limit(3).all())
const { data: home } = await useAsyncData('home-page', () => queryCollection('pages').path('/pages/beranda').first())
usePageSeo('Beranda — Konstruksi untuk Masa Depan', () => home.value?.description || 'Solusi konstruksi PT Alpha Tunas Mandiri', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2000&q=85')
</script>
<template><div><HeroSection/><div class="principles"><div class="shell"><span class="eyebrow">KOMITMEN DALAM SETIAP LANGKAH</span><span><UIcon name="i-lucide-drafting-compass"/> Perencanaan Matang</span><span><UIcon name="i-lucide-shield-check"/> Mutu & Keselamatan</span><span><UIcon name="i-lucide-handshake"/> Kolaborasi Terbuka</span></div></div><RevealSection><section id="tentang" class="section shell about-preview"><div class="about-image"><img src="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=85" alt="Ilustrasi tim konstruksi bekerja di lapangan" loading="lazy" width="800" height="900"/><div class="image-note"><span>01—04</span><p>Dari gagasan<br>hingga serah terima.</p></div></div><div><p class="eyebrow">TENTANG ALPHA TUNAS MANDIRI</p><h2>Lebih dari bangunan.<br>Sebuah <em>kepercayaan.</em></h2><div class="intro-prose"><ContentRenderer v-if="home" :value="home"/></div><p class="muted">Kami menghubungkan perencanaan, pelaksanaan, dan perhatian pada detail untuk menghadirkan solusi yang sesuai dengan kebutuhan Anda.</p><div class="about-points"><span><UIcon name="i-lucide-check"/> Lingkup pekerjaan yang jelas</span><span><UIcon name="i-lucide-check"/> Komunikasi di setiap tahap</span><span><UIcon name="i-lucide-check"/> Hasil yang berorientasi fungsi</span></div><UButton to="/tentang-kami" label="Kenali Perusahaan Kami" color="neutral" variant="outline" trailing-icon="i-lucide-arrow-up-right" size="lg"/></div></section></RevealSection>
<RevealSection><section class="section surface"><div class="shell"><div class="section-heading"><div><p class="eyebrow">LAYANAN & JASA</p><h2>Satu mitra.<br>Beragam solusi.</h2></div><div><p>Dukungan menyeluruh untuk setiap<br>kebutuhan pembangunan Anda.</p><NuxtLink to="/layanan" class="text-link">Semua Layanan <UIcon name="i-lucide-arrow-up-right"/></NuxtLink></div></div><div class="service-grid"><NuxtLink v-for="(service, i) in services" :key="service.path" :to="service.path" class="service-card"><div class="service-top"><UIcon :name="service.icon"/><span>0{{ i + 1 }}</span></div><h3>{{ service.title }}</h3><p>{{ service.description }}</p><span class="service-arrow"><UIcon name="i-lucide-arrow-up-right"/></span></NuxtLink></div></div></section></RevealSection>
<RevealSection><section class="section shell"><div class="section-heading"><div><p class="eyebrow">GALERI PROYEK</p><h2>Ruang untuk<br>kemungkinan baru.</h2></div><div><p>Eksplorasi bentuk, fungsi, dan detail.<br>Portofolio ilustratif pilihan kami.</p><NuxtLink to="/galeri" class="text-link">Jelajahi Galeri <UIcon name="i-lucide-arrow-up-right"/></NuxtLink></div></div><div class="cards three"><ContentCard v-for="project in projects" :key="project.path" :item="project"/></div><p class="caption">Proyek dan foto di atas merupakan ilustrasi untuk pratinjau website.</p></section></RevealSection>
<section class="process section"><div class="shell"><div class="section-heading"><div><p class="eyebrow">CARA KAMI BEKERJA</p><h2>Langkah yang jelas.<br>Tujuan yang sama.</h2></div><p>Proses yang terarah membuat setiap<br>keputusan menjadi lebih berarti.</p></div><div class="steps"><div v-for="(step, i) in company?.steps" :key="step.title"><span class="step-number">0{{ i + 1 }}</span><h3>{{ step.title }}</h3><p>{{ step.description }}</p></div></div></div></section>
<RevealSection><section class="section shell"><div class="section-heading"><div><p class="eyebrow">ARTIKEL & WAWASAN</p><h2>Perspektif untuk<br>membangun lebih baik.</h2></div><NuxtLink to="/artikel" class="text-link">Semua Artikel <UIcon name="i-lucide-arrow-up-right"/></NuxtLink></div><div class="cards three"><ContentCard v-for="article in articles" :key="article.path" :item="article"/></div></section></RevealSection><section class="section surface"><div class="shell faq-grid"><div><p class="eyebrow">SEBELUM MEMULAI</p><h2>Ada yang ingin<br>Anda ketahui?</h2><NuxtLink to="/faq" class="text-link">Semua Pertanyaan <UIcon name="i-lucide-arrow-right"/></NuxtLink></div><UAccordion :items="company?.faq?.slice(0, 4) || []"/></div></section><ContactCta/></div></template>

